### ISSUE TITLE
Extending from Error not supported

### ISSUE THREAD

**Issue by wesleytodd** [Raynos/is-error#2]
Seems like this module should also support custom errors that are extended from the Error object.  Is there a reason this is not supported?  Seems like this would do the trick:

``` javascript
function isError(err) {
    return objectToString.call(err) === ERROR_TYPE || typeof Error !== 'undefined' ? err instanceof Error  false;
}
```

If you like this change I will submit a PR.  Otherwise I will probably for this module.

**Comment by wesleytodd** [comment]
Sorry, copy and pasting our of vim sometimes screws up:

``` javascript
function isError(err) {
    return objectToString.call(err) === ERROR_TYPE || typeof Error !== 'undefined' ? err instanceof Error false;
}
```

**Comment by wesleytodd** [comment]
So for some reason i thought that in some old IE `instanceof Error` didn't work.  But I guess it does, which makes this simpler:

``` javascript
return objectToString.call(err) === ERROR_TYPE || err instanceof Error;
```

**Comment by Raynos** [comment]
@wesleytodd we loop through the prototype chain so it should work!

have you tried updating to the latest version?

**Comment by wesleytodd** [comment]
Hmmm, it was a fresh install from yesterday.  Looking at the code on github it should work, and it is totally different than the code npm gave me.  Ill look into it.  Thanks!

**Comment by wesleytodd** [comment]
Ok, anyone got an explanation for this?  Lol, npm messing up?

![messed-up-version](https://cloud.githubusercontent.com/assets/1027776/7554943/24b2d318-f700-11e4-91f7-8ea18cf3aab0.png)

EDIT:  This was taken right after removing it from node_modules, clearing npm cache, and re-installing.

**Comment by Raynos** [comment]
@wesleytodd looks like npm@2.1.0 was never published. I just published it. Sorry!

**Comment by wesleytodd** [comment]
Haha, well I just assumed that 2.0 was your new version.  Thanks!!
