### ISSUE TITLE
AssertionErrors aren't errors?

### ISSUE THREAD

**Issue by mk-pmb** [Raynos/is-error#4]
``` javascript
'use strict';

var isError = require('is-error'), assert = require('assert'), x;

x = new assert.AssertionError({ message: 'nope.' });
assert.strictEqual(true,  (x instanceof Error));
assert.strictEqual(false, isError(x));

// EDIT: found the problem.
assert.strictEqual((typeof x), 'object');
assert.strictEqual(Object.prototype.toString.call(x), '[object Object]');


x = null;
try {
  assert.strictEqual(1, 2);
} catch (caught) {
  x = caught;
}
assert.strictEqual(true,  (x instanceof Error));
assert.strictEqual(false, isError(x));

console.log(process.versions.node);   //= "6.1.0"
```

Why does it print my node version? Using is-error@2.2.0

**Comment by mk-pmb** [comment]
I'd suggest a fast opportunistic `(x instanceof Error)` check before climbing the prototypes, but I don't have a good idea on how to have that not voiding the tests for the climbing. Maybe the check function could be generated by a factory that has a flag for it.

**Comment by mk-pmb** [comment]
Anyone reading here who can fix this, or shall I just make a new module?

**Comment by Raynos** [comment]
@mk-pmb was gonna transfer this module to you, but you already have a fork :(

**Comment by mk-pmb** [comment]
I've deleted my fork. :-)

**Comment by Raynos** [comment]
@mk-pmb 

```
raynos at raynos-Dell-Precision-M3800  ~/projects/jsig on gh-pages*
$ npm owner ls is-error
npm http request GET https://registry.npmjs.org/is-error
npm http 200 https://registry.npmjs.org/is-error
jcorbin <jcorbin@wunjo.org>
kriskowal <kris.kowal@cixar.com>
mk-pmb <mk+npmjs@pimpmybyte.de>
raynos <raynos2@gmail.com>
```

**Comment by mk-pmb** [comment]
Thanks! I'll add the shortcut fix asap, then try and figure out the tests so I can dare tackling harder bugs in case some might emerge.

**Comment by Raynos** [comment]
@mk-pmb Thanks for the hustle. Appreciate it.
