### ISSUE TITLE
Tidelift 

### ISSUE THREAD

**Issue by Raynos** [Raynos/is-error#6]
I'm going through the process of updating packages I have authored on https://tidelift.com/ ;

This package should have any tidelift income shared between myself and @mk-pmb , for that both of us would have to sign up to tidelift, also happy to discuss over email or twitter.

**Comment by mk-pmb** [comment]
If you see a way to make money off of this project (in compliance with the license). feel free to do so and donate some of it to me. :-) You can reach me via email at `mk (plus) copyleft (guess a symbol) pimpmybyte.de`. We can postpone discussion of donation methods until you have a stack that's worth pondering the transaction fees.

**Comment by mk-pmb** [comment]
Also sorry for the wording of the license reminder. I should have checked the commit history first. Obviously my one actual patch pales in comparison to your work. :D

**Comment by mk-pmb** [comment]
To anyone interested, I decided to let @Raynos take all the money, as it's mostly his work still and Tidelift currently isn't worth the effort for me. (Most of the effort being German tax and regulations stuff.)
